services:
  # 1. PostgreSQL 데이터베이스
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      TZ: Asia/Seoul
    ports:
      - "8432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    networks:
      - ssafy-network

  # 2. Jenkins
  jenkins:
    build:
      context: ./jenkins
      dockerfile: Dockerfile
    container_name: jenkins-server
    restart: always
    group_add:
      - "${DOCKER_GID}"
    ports:
      - "8501:8080"
      - "50000:50000"
    environment:
      - TZ=Asia/Seoul
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/ubuntu/projects:/home/ubuntu/projects
    networks:
      - ssafy-network
  
  # 3. Redis
  redis:
    image: redis:alpine
    container_name: redis-server
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    ports:
      - "8379:6379"
    volumes:
      - ./redis_data:/data
    networks:
      - ssafy-network
      
  # 4. LiveKit
  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: always
    command: --config /etc/livekit.yaml --node-ip ${LIVEKIT_IP}
    ports:
      - "8880:7880"
      - "51000-51100:51000-51100/udp"
      - "51000-51100:51000-51100/tcp"
    volumes:
      - ./livekit.yaml:/etc/livekit.yaml
    environment:
      LIVEKIT_KEYS: "${LIVEKIT_API_KEY}: ${LIVEKIT_API_SECRET}"
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - redis
    networks:
      - ssafy-network

networks:
  ssafy-network:
    name: ssafy-network
    driver: bridge